// Rendering: data/index.json -> README.md.
// Kept apart from the pipeline so the README can be regenerated from the
// committed index alone — a pull request never needs the caches.

import { readFile, writeFile } from 'node:fs/promises';
import { CATEGORY_LABELS, CATEGORY_ORDER } from './lib/taxonomy.mjs';

const at = (p) => new URL(`../${p}`, import.meta.url);

const STATUS_MARK = { active: '🟢', stale: '🟡', dormant: '⚪', archived: '📦', external: '🔗' };

function row(e) {
  const link = `[${e.name}](${e.url})`;
  const desc = (e.description ?? '').replace(/\|/g, '\\|');
  const proof = e.evidence[0]?.source?.url
    ? `[${e.evidence[0].kind}](${e.evidence[0].source.url})`
    : '—';
  const stars = e.stars == null ? '—' : e.stars.toLocaleString('en-US');
  return `| ${link} | ${desc} | ${e.language ?? '—'} | ${e.license ?? '—'} | ${stars} | ${proof} | ${STATUS_MARK[e.status]} |`;
}

export function renderReadme(index) {
  const { counts, entries } = index;
  const date = index.generatedAt.slice(0, 10);
  const out = [];

  out.push('# Jevsome Projects');
  out.push('');
  out.push('> Every open-source project we can **prove** calls Jev, TypeSafe AI\'s System One model.');
  out.push('');
  out.push(`**${counts.total} projects · ${counts.stars.toLocaleString('en-US')} stars · refreshed ${date} · ${counts.rejected.unverified} candidates rejected for lack of proof**`);
  out.push('');
  out.push('Other Jev lists are hand-curated link dumps. This one is a pipeline:');
  out.push('');
  out.push('1. **Discovery** searches GitHub code and repositories directly — no entry is copied from another list.');
  out.push('2. **Evidence** links each entry to the file that proves it: the `/v1/systemone` call, the pinned `jev-latest` route, or the declared SDK dependency. A mention in a README is a claim, not proof — documentation matches are rated down and do not earn an entry.');
  out.push(index.classifiedBy?.jev
    ? `3. **Classification** is done by Jev itself, one typed \`choice\` per repository (${index.classifiedBy.jev} of ${counts.total} entries; the rest fall back to keyword rules).`
    : '3. **Classification** currently runs on keyword rules. The Jev path is wired up and takes over as soon as a `TYPESAFE_API_KEY` is configured — see [`pipeline/classify.mjs`](pipeline/classify.mjs).');
  out.push('4. **Health** re-checks stars, licences, last commit and demo links every day.');
  out.push('');
  out.push('Everything below is generated from [`data/index.json`](data/index.json). Do not edit this file by hand — see [CONTRIBUTING.md](CONTRIBUTING.md).');
  out.push('');
  out.push('🟢 active (30d) · 🟡 stale (90d) · ⚪ dormant · 📦 archived · 🔗 external');
  out.push('');
  out.push('## Contents');
  out.push('');
  for (const cat of CATEGORY_ORDER) {
    const n = counts.byCategory[cat] ?? 0;
    if (!n) continue;
    const label = CATEGORY_LABELS[cat];
    out.push(`- [${label}](#${label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}) (${n})`);
  }
  out.push('');

  for (const cat of CATEGORY_ORDER) {
    const list = entries.filter((e) => e.category === cat);
    if (!list.length) continue;
    out.push(`## ${CATEGORY_LABELS[cat]}`);
    out.push('');
    out.push('| Project | What it does | Language | License | Stars | Evidence | Status |');
    out.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const e of list) out.push(row(e));
    out.push('');
  }

  out.push('## License');
  out.push('');
  out.push('The list and the pipeline are released under [CC0 1.0](LICENSE). Linked projects keep their own licences.');
  out.push('');
  out.push('Not affiliated with TypeSafe AI.');
  out.push('');
  return out.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const index = JSON.parse(await readFile(at('data/index.json'), 'utf8'));
  await writeFile(at('README.md'), renderReadme(index));
  console.log(`render: README.md with ${index.entries.length} entries`);
}
